[draft] dynamodb instrumentation
newrelic/node-newrelic-aws-sdk pull request #110
Opened 2021-11-17 22:01 UTC by garbados

## Proposed Release Notes

## Links

## Details

2021-11-18 02:45 UTC, garbados commented
Tests pass! At least, on the local commit I haven't pushed yet 😅 

Some concerns:

- At instrumentation-time, it seems we don't yet have a `requestId` because the request hasn't actually occurred, so our attribute tests had to be modified a bit to fit this changed expectation. If anyone knows how to get the requestId, I'm all ears!
- This PR bites a lot of code from https://github.com/newrelic/node-newrelic-aws-sdk/pull/109, suggesting that such logic should be extracted to a common file, especially as we plan to apply this middleware approach to [other areas as well](https://github.com/newrelic/node-newrelic-aws-sdk/pull/107#issuecomment-972029980).
- This PR adds the `server.destroy` convenience method to `createEmptyResponseServer`, based on [this patch](https://github.com/garbados/node-newrelic-aws-sdk/pull/1). Because it shows up in both mock servers, it too should be extracted to a common location.

Thanks to @bizob2828 for his help on getting this PR together!

2021-11-18 02:50 UTC, garbados commented
Hm, exciting! Failures! I'll check it out in the morning.

2021-11-18 12:05 UTC, bizob2828 commented
> At instrumentation-time, it seems we don't yet have a requestId because the request hasn't actually occurred, so our attribute tests had to be modified a bit to fit this changed expectation. If anyone knows how to get the requestId, I'm all ears!

None of the attributes will exist on segment because #106 hasn't been merged.

2021-11-18 14:50 UTC, bizob2828 commented on lib/v3-dynamo-ddb.js
> +      'product': this.serviceId,
this stuff should be in the core instrumentation(#106).  If you're unclear you should be using https://github.com/newrelic/node-newrelic-aws-sdk/blob/main/lib/dynamodb.js#L44 as a reference.  Also you're grabbing the command  on line 84 and probably should use that instead of referencing the contructor.name

2021-11-18 14:51 UTC, bizob2828 commented on lib/v3-dynamo-ddb.js
> +    opaque: true
I think you also need to pass `promise: true` as this can be both cb and promise based

2021-11-18 15:02 UTC, bizob2828 commented on index.js
> +newrelic.instrumentMessages('@aws-sdk/client-dynamodb', require('./lib/v3-dynamo-ddb'))
this won't work as the default behavior is to handle the 2nd arg as `onRequire` not `onResolved`. You can pass an object similar to how you're doing it in `nr-hooks.js`

2021-11-18 15:03 UTC, bizob2828 commented on package.json
> +    "@aws-sdk/client-dynamodb": "^3.41.0"
i think you may have mistakenly added this while testing. this should be wired up in `tests/versioned/aws-sdk-v3/package.json`

2021-11-19 00:41 UTC, garbados commented on package.json
> +    "@aws-sdk/client-dynamodb": "^3.41.0"
Indeed 😞

2021-11-19 16:47 UTC, bizob2828 requested changes

2021-11-19 16:47 UTC, bizob2828 commented on index.js
> +newrelic.instrumentMessages({
not a big deal but this was done in #109

2021-11-19 16:47 UTC, bizob2828 commented on index.js
> +newrelic.instrumentMessages({
this is a datastore, so i think you need to use `instrumentDatastore`

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +    function wrappedReturn(shim, fn, name, instance) {
i would fix this warning. it was suggested by @michaelgoin in my PRs.

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> + * a plugin that adds a middleware to record the time it teakes to publish a message
this comment is incorrect

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +  // eslint-disable-next-line consistent-return
not sure this is needed is it?

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +  const port_path_or_id = this.endpoint && this.endpoint.port
there is a reason we have this linting rule. i wouldn't ignore it and just make var camel case

2021-11-19 16:47 UTC, bizob2828 commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +    return [
we're missing some commands:
 * batch execute
 * batch get
 * batch write
 * update table

2021-11-19 16:47 UTC, bizob2828 commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +  t.test('commands', async (t) => {
you may want to also have a test that uses the callback style

2021-11-19 16:47 UTC, bizob2828 commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +      const attrs = segment.attributes.get(common.SEGMENT_DESTINATION)
most of the other suites check all the aws.* values as well.

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +      getDynamoSpec.bind({
i don't see region nor serviceId getting used in the function below

2021-11-19 16:47 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +    name: command.constructor.name,
all the other instrumentation get this from the context on middleware.  It may be best for consistency and also not looking up via the constructor's name property

2021-11-19 16:47 UTC, bizob2828 commented on tests/versioned/aws-server-stubs/common.js
> +exports.patchDestroy = function (server) {
💯 nice abstraction

2021-11-19 16:47 UTC, bizob2828 commented on tests/versioned/aws-server-stubs/empty-response-server/index.js
> +  // patch server.destroy
nit but i think the function name provides enough context where the comment is unnecessary

2021-11-19 18:58 UTC, garbados commented on lib/v3-client-dynamodb.js
> +      getDynamoSpec.bind({
Ah, yeah, that was from before I integrated the Smithy instrumentation. I'll remove it.

2021-11-19 18:58 UTC, garbados commented on tests/versioned/aws-server-stubs/empty-response-server/index.js
> +  // patch server.destroy
Fair enough.

2021-11-19 19:00 UTC, garbados commented on lib/v3-client-dynamodb.js
> +  const port_path_or_id = this.endpoint && this.endpoint.port
So, the reason I did it this way is that this is what the variable is named in the v2 instrumentation: https://github.com/newrelic/node-newrelic-aws-sdk/blob/main/lib/dynamodb.js#L48

Are we OK changing this to `portPathOrId`?

2021-11-19 19:03 UTC, garbados commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +      const attrs = segment.attributes.get(common.SEGMENT_DESTINATION)
Doesn't `checkAWSAttributes` check those automatically? https://github.com/newrelic/node-newrelic-aws-sdk/blob/main/tests/versioned/common.js#L16-L21

2021-11-19 19:04 UTC, bizob2828 commented on lib/v3-client-dynamodb.js
> +  const port_path_or_id = this.endpoint && this.endpoint.port
oh so the key in parameters should be `port_path_or_id` but this is just a variable that is getting used as the key.  so maybe you can just put this into the parameters as `port_path_or_id: this.endpoint && this.endpoint.port`

2021-11-19 22:49 UTC, garbados commented on index.js
> +newrelic.instrumentMessages({
Fixed in merge.

2021-11-19 22:55 UTC, garbados commented on lib/v3-client-dynamodb.js
> +    function wrappedReturn(shim, fn, name, instance) {
Fix what warning? The debug statement on line 33?

2021-11-19 23:16 UTC, garbados commented on lib/v3-client-dynamodb.js
> +    function wrappedReturn(shim, fn, name, instance) {
Ah, got it. Thanks.

2021-11-19 23:17 UTC, garbados commented on lib/v3-client-dynamodb.js
> +  // eslint-disable-next-line consistent-return
Fixed; it was bothering me too, but I plucked it from another file to observe convention.

2021-11-19 23:23 UTC, garbados commented on lib/v3-client-dynamodb.js
> +  const port_path_or_id = this.endpoint && this.endpoint.port
I couldn't resist the allure of the one-liner:

`parameters: { host, port_path_or_id: portPathOrId, collection },`

2021-11-20 01:07 UTC, garbados commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +  t.test('commands', async (t) => {
So, I wrote callback-style tests, but they fail for want of `aws.*` attributes. This implies that the Smithy instrumentation isn't affecting them, but I didn't have time today to look into it much. Would you write some callback-style tests for your lib-dynamodb instrumentation and see if you get the same problem?

The test in question, commented out: https://github.com/newrelic/node-newrelic-aws-sdk/pull/110/files#diff-4084fb2a2bb847765aeab072c279d34a34608b6c5b95afe1f38bb9bc12feb2afR124-R142

2021-11-20 01:08 UTC, garbados commented
Responded to all @bizob2828 's feedback, thanks again for the thorough review :)

2021-11-22 16:11 UTC, bizob2828 commented on tests/versioned/aws-sdk-v3/client-dynamodb.tap.js
> +      const attrs = segment.attributes.get(common.SEGMENT_DESTINATION)
it' checks the types not the actual values

2021-11-22 16:40 UTC, bizob2828 approved these changes
I fixed the callback style tests and also assert all AWS.* attrs in the finish command.  Good work on this one

2021-11-22 16:50 UTC, bizob2828 approved these changes

2021-11-22 17:16 UTC, merged