AWS-SDK v3 abstractions
newrelic/node-newrelic-aws-sdk pull request #113
Opened 2021-11-30 00:55 UTC by garbados

## Proposed Release Notes

## Links

- https://github.com/newrelic/node-newrelic-aws-sdk/issues/104

## Details

This PR re-organizes the files in this repo around which version of the SDK they handle, and abstracts some common features of v3 instrumentation into a util file.

This PR branches off https://github.com/newrelic/node-newrelic-aws-sdk/pull/107 and can be considered a research PR; we can do another PR later, once the AWS SDK v3 is fully instrumented.

2021-11-30 22:41 UTC, garbados commented
A quick rundown of what this PR does:

- Separates v2 and v3 instrumentation under `lib/` into `lib/v(2,3)` and under `tests/versioned/` into `tests/versioned/v{2,3}`
- Names v3 instrumentation after the modules being instruments, ex: `client-dynamodb.js`, `lib-dynamodb.js`
- Extracts common logic into a couple util files, particularly `lib/v3/util.js` and `lib/v3/dynamodb-util.js`

This PR isn't "complete" as there is more logic extraction to do, and potentially more renaming too. I leave it in this state in order to solicit comments before I proceed further on the subject.

2021-12-02 00:24 UTC, garbados commented
I think I'm done on my end with this. I'm interested in @bizob2828 's perspective on this, particularly pertaining to https://github.com/newrelic/node-newrelic-aws-sdk/issues/104

2021-12-02 17:09 UTC, bizob2828 requested changes
overall this looks great.  I really like the abstractions to cut down on boilerplate.  a few comments

2021-12-02 17:09 UTC, bizob2828 commented on lib/v3/dynamodb-util.js
> +      if (commands.includes(commandName)) {
dynamo is the only client where this is relevant now but perhaps have an else that just applies a debug logger stating we aren't recording operation because it's not a supported command.  [See](https://github.com/newrelic/node-newrelic-aws-sdk/pull/105#discussion_r744020917)

2021-12-02 17:09 UTC, bizob2828 commented on lib/v3/dynamodb-util.js
> +function getDynamoSpec(shim, original, name, args) {
def what i was expecting for dynamo abstractions 👏🏻

2021-12-02 17:09 UTC, bizob2828 commented on lib/v3/sns.js
>    if (context.commandName === 'PublishCommand') {
similar a comment in dynamodb-util, we should prob add a logger debug on else that we aren't recording based on command

2021-12-02 17:09 UTC, bizob2828 commented on lib/v3/sqs.js
> +const { grabLastUrlSegment } = require('../util')
line 62 in this file should also have a logger else that states we aren't recording the operation

2021-12-02 22:52 UTC, garbados commented
My only ongoing concern here is that the v3 tests take 5-6x longer to run than the v2 tests, mostly because the v3 modules take significantly longer to install. Not sure if we can do anything about this, though.

2021-12-02 22:53 UTC, garbados commented
Feedback addressed! We now record all DynamoDB commands, rather than a select few.

2021-12-03 01:06 UTC, garbados commented on lib/v3/lib-dynamodb.js
> +const COMMANDS = [
Added!

2021-12-06 17:12 UTC, bizob2828 approved these changes

2021-12-06 18:15 UTC, merged