Addressing Node 18 todos
newrelic/node-newrelic-aws-sdk pull request #140
Opened 2022-07-20 21:18 UTC by mrickard

Removed agent version check as per TODOs
Removed unused semver dependency
Addressed linter warning 
Bumped version

<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2022-07-20 21:28 UTC, michaelgoin commented
I think what is implied with that comment is that we'd update the peer dependency field to require the minimum version of the agent as a breaking (semver major) change along with the add Node 18 / Drop Node 12 work. That is what allows us to safely drop the semver check from this module.

@bizob2828 does that align with your memory?

As such, I think you'll want to update the peer dependency field for `newrelic` in package.json to be >= 8.7.0 and we can slap a semver: major on label on this PR. I don't think we need to hold off merging as I don't expect any changes to come in prior to starting the major release process.

2022-07-21 19:43 UTC, bizob2828 commented
> 

Yea I was just thinking through this and I think this is correct.

2022-07-21 19:44 UTC, bizob2828 requested changes

2022-07-21 19:44 UTC, bizob2828 commented on package.json
> -  "version": "4.1.2",
this is something we do as part of releasing and should not be touched in a different PR

2022-07-21 19:44 UTC, bizob2828 commented on tests/versioned/v3/client-dynamodb.tap.js
> -  function finish(t, commands, tx) {
was there a reason for this change. it's fine but doesn't seem necesssary

2022-07-21 19:45 UTC, mrickard commented on package.json
> -  "version": "4.1.2",
Ah, ok. I wasn't sure if this was handled in github hooks, or if we had to bump versions manually.

2022-07-21 19:46 UTC, mrickard commented on tests/versioned/v3/client-dynamodb.tap.js
> -  function finish(t, commands, tx) {
I was getting linter complaints about `commands` being shadowed in this inner scope, so I changed it to remove the warning.

2022-07-21 19:46 UTC, mrickard commented on package.json
> -  "version": "4.1.2",
I'll restore the version.

2022-07-21 19:47 UTC, bizob2828 commented on package.json
> -  "version": "4.1.2",
Yea so when we get ready to release this. we will prepare release by running https://github.com/newrelic/node-newrelic-aws-sdk/actions/workflows/prepare-release.yml, and picking `major` as the version which will open a PR with updates to changelog and properly update the package.json and package-lock with the new version

2022-07-21 20:22 UTC, mrickard commented on package.json
> -  "version": "4.1.2",
I've restored the previous version, so this should be re-reviewable.

2022-07-21 20:35 UTC, bizob2828 approved these changes

2022-07-21 20:35 UTC, merged