ci: updated smoke tests to run npm install to get latest and console log the version so we know what is being tested in CI
newrelic/node-newrelic-aws-sdk pull request #191
Opened 2023-05-31 21:05 UTC by bizob2828

## Details
Realized our smoke tests pin the aws version so we can't test newer versions. Also logging it out.

2023-05-31 21:07 UTC, bizob2828 commented on tests/smoke/v3/client-s3.test.js
> +    console.log(`AWS Version: ${version}`)
wanted to use `t.comment` but our reporter hides those on passing suites

2023-06-01 14:18 UTC, jmartin4563 requested changes
Confirmed locally that `console.log` is output when running the smoke tests with this PR checked out, just had two small thoughts

2023-06-01 14:18 UTC, jmartin4563 commented on tests/smoke/v3/client-s3.test.js
> +    console.log(`AWS Version: ${version}`)
Two things: one: can we add a eslint ignore to the console log line and two: should we also add this to the request presigner test?

2023-06-01 16:09 UTC, jmartin4563 approved these changes

2023-06-01 16:56 UTC, merged