feat: Add initial objects for LLM events
newrelic/node-newrelic-aws-sdk pull request #236
Opened 2024-01-03 15:04 UTC by jsumners-nr

This PR is to resolve #223.

I have left out a lot of defensive checks because I'm not clear how the objects will be used at the moment. I've tried to implement the CDD as closely as possible in such a way as to provide a baseline that can be tweaked and completed as the actual instrumentation is written.

Since some of the class syntax is newer than the ECMAScript version configured for the linter on the main branch, this PR also updates all of the linting tooling.

2024-01-03 21:40 UTC, bizob2828 requested changes
this will prob take a few iterations.  Here's a [commit](https://github.com/bizob2828/node-newrelic-aws-sdk/commit/4ff81b8bdefe911eeaa528a46aff74ec653c62e6) that shows instrumentation in action and an attempt to create the relevant chat completion messages/summary.

this is also a [commit](https://github.com/bizob2828/node-newrelic-aws-sdk/commit/5dd2801dd51d0675b9c2177255c91ba4ade7178f) where i attempted to start fixing but got overwhelmed.  Overall it's close aside from the execution of creating chat completion messages.  they need to be done in a loop to pass in the index which i linked in the comments of the commits above.  we can sync up in morning as well

2024-01-03 21:40 UTC, bizob2828 commented on lib/llm/event.js
> +    const attrs = tx?.trace?.custom.get('TODO')
hmm so this is a bitwise operator in `lib/config/attributes-filter.js` within agent.

2024-01-03 21:40 UTC, bizob2828 commented on lib/llm/chat-completion-summary.js
> +  #setMaxTokens() {
I think these key accessors need to be more defensive just in case

2024-01-03 21:40 UTC, bizob2828 commented on lib/llm/event.js
> +    this.sequence = -1
this is passed in as the index on creating of all the chat completion messages

2024-01-03 21:43 UTC, bizob2828 commented on lib/llm/chat-completion-message.js
> +    const event = new LlmChatCompletionMessage(params)
this only exists on summary and embedding

2024-01-03 21:43 UTC, bizob2828 commented on lib/llm/event.js
> +  static async create(params = createDefaultParams) {
this only exists on summary and embedding

2024-01-04 16:42 UTC, bizob2828 commented on lib/llm/chat-completion-message.js
> +    return Object.keys(response).length > 0
the algorithm in openai is the first response content matches the message content: https://github.com/newrelic/node-newrelic/blob/main/lib/llm-events/openai/chat-completion-message.js#L18

2024-01-04 21:45 UTC, bizob2828 requested changes
this is much better. i'm glad after back and forth we landed on some command and response parser separate from the llm messages, nice work. 

I have a patch of fixes/suggestions from using it
[changes.patch](https://github.com/newrelic/node-newrelic-aws-sdk/files/13835724/changes.patch)

Lastly, can I ask that you create an `lib/llm/index.js` and export all the classes as named exports so i can just destructure it all from `const { LlmChatCompletionMessage,... } = require('../llm/')`

2024-01-04 22:15 UTC, bizob2828 commented on lib/llm/chat-completion-summary.js
> +    this[cfr] = cmd.finishReason
```suggestion
    this[cfr] = this.bedrockResponse.finishReason
```

2024-01-04 22:15 UTC, bizob2828 commented on lib/llm/bedrock-response.js
> +      result = this.#parsedBody.results?.[0]?.finishReason.reason
```suggestion
      result = this.#parsedBody.completions?.[0]?.finishReason.reason
```

2024-01-05 12:38 UTC, jsumners-nr commented
For easier reference:

```diff
diff --git a/lib/llm/bedrock-command.js b/lib/llm/bedrock-command.js
index 8548581..bf397bf 100644
--- a/lib/llm/bedrock-command.js
+++ b/lib/llm/bedrock-command.js
@@ -14,13 +14,12 @@ class BedrockCommand {
   #modelId
 
   /**
-   * @param {object} params
-   * @param {object} params.invokeCommand The InvokeModelCommand or
+   * @param {object} input The InvokeModelCommand or
    * InvokeModelWithResponseStreamCommand instance that is used for the
    * conversation.
    */
-  constructor({ invokeCommand }) {
-    this.#input = invokeCommand.input
+  constructor(input) {
+    this.#input = input
     this.#body = JSON.parse(this.#input.body)
     this.#modelId = this.#input.modelId.toLowerCase()
   }
@@ -32,10 +31,10 @@ class BedrockCommand {
    *
    * @returns {boolean}
    */
-  static isEmbeddingModel(modelId) {
+  get modelType() {
     // At the moment, this is a simple check. If Amazon ever introduces a
     // complex identifier, we can implement a more complicated check.
-    return modelId.toLowerCase().includes('embed')
+    return this.#modelId.toLowerCase().includes('embed') ? 'embedding' : 'completion'
   }
 
   /**
diff --git a/lib/llm/bedrock-response.js b/lib/llm/bedrock-response.js
index 64db905..3a2fa67 100644
--- a/lib/llm/bedrock-response.js
+++ b/lib/llm/bedrock-response.js
@@ -38,11 +38,13 @@ class BedrockResponse {
     const cmd = this.#command
     if (cmd.isAi21() === true) {
       this.#completions = this.#parsedBody.completions.map((c) => c.data.text)
+      this.id = this.#parsedBody.id
     } else if (cmd.isClaude() === true) {
       // TODO: can we make this thing give more than one completion?
       this.#completions.push(this.#parsedBody.completion)
     } else if (cmd.isCohere() === true) {
       this.#completions = this.#parsedBody.generations.map((g) => g.text)
+      this.id = this.#parsedBody.id
     } else if (cmd.isTitan() === true) {
       this.#completions = this.#parsedBody.results.map((r) => r.outputText)
     }
diff --git a/lib/llm/chat-completion-message.js b/lib/llm/chat-completion-message.js
index 8f55620..916fc18 100644
--- a/lib/llm/chat-completion-message.js
+++ b/lib/llm/chat-completion-message.js
@@ -61,7 +61,7 @@ class LlmChatCompletionMessage extends LlmEvent {
     if (cmd.isTitan() === true || cmd.isClaude() === true) {
       this.id = `${this.id}-${index}`
     } else if (cmd.isAi21() === true || cmd.isCohere() === true) {
-      this.id = `${this.response.id}-${index}`
+      this.id = `${this.bedrockResponse.id}-${index}`
     }
   }
 }
```

2024-01-05 18:55 UTC, bizob2828 requested changes
overall looks good just a few questions/issues. I noticed the addition of those unit tests it no longer runs the `test/unit/utils.tap.js` file when i run` npm run unit`

2024-01-05 18:55 UTC, bizob2828 commented on lib/llm/chat-completion-summary.js
>      this[upt] = parseInt(this.bedrockResponse.headers['x-amzn-bedrock-input-token-count'] || 0, 10)
this isn't using the new `this.bedrockResponse.inputTokencount`

2024-01-05 18:55 UTC, bizob2828 commented on tests/unit/llm/bedrock-response.tap.js
> +tap.test('non-conforming response is handled gracefully', async (t) => {
when i run the tests locally and look at the coverage this for some reason isn't hitting the else statement where it defaults to 0

2024-01-05 19:04 UTC, bizob2828 commented on tests/unit/llm/bedrock-response.tap.js
> +tap.test('non-conforming response is handled gracefully', async (t) => {
oh i see why, it's cuz the test is removing all the headers. if we just do this, the branch is covered better

```js
tap.test('non-conforming response is handled gracefully', async (t) => {
  delete t.context.response.response.headers['x-amzn-bedrock-input-token-count']
  const res = new BedrockResponse(t.context)
  t.same(res.completions, [])
  t.equal(res.finishReason, undefined)
  //t.same(res.headers, undefined)
  t.equal(res.id, undefined)
  t.equal(res.inputTokenCount, 0)
  t.equal(res.requestId, 'aws-request-1')
  t.equal(res.statusCode, 200)
})
```

2024-01-05 19:48 UTC, bizob2828 approved these changes

2024-01-05 19:48 UTC, merged